### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [dajwill/railsAuth#1]
My login information doesn't seem to be working on Heroku. Did you make sure to add the user to Heroku's database as well?

**Comment by dajwill** [comment]
Added you as authorized user.

**Comment by chrisvfritz** [comment]
Hmm, still doesn't seem to be working for me. Did you just do so locally with `rails console`, or did you also add the user to Heroku's database with `heroku run rails console`?

**Comment by dajwill** [comment]
@chrisvfritz  your user name should be working now.

**Comment by chrisvfritz** [comment]
Excellent! One more thing I see that needs updating: I still see an Edit link on the Show page when I'm not logged in, when it should only be visible when I *am* logged in.

**Comment by dajwill** [comment]
Just pushed the fix

**Comment by chrisvfritz** [comment]
:+1: Looks good!
